### ISSUE TITLE
ap37.print function so slow

### ISSUE THREAD

**Issue by fagcinsk** [apseren/ap37#1]
When I use it inside two "for" loops, it takes several seconds on Xiaomi Redmi Note 3 pro.
Do u use DOM element for each character? How strings are painting?

**Comment by fagcinsk** [comment]
Btw, how can I cleanup whole screen?

**Comment by apseren** [comment]
The current implementation draws the characters on an Android Bitmap using Canvas.drawText, might change in the future.

No specific method to clear the whole screen is currently implemented. But you can accomplish the same effect by printing an empty string.
