### ISSUE TITLE
Printing DateTime in 12Hour format with AM/PM

### ISSUE THREAD

**Issue by adriancs2** [apseren/ap37#10]
Can you try to figure out a way to print the datetime in 12 Hour format with (AM/PM sign) in stead of 24 Hour format?
Perhaps a boolean value to identify the switch for 12H/24H?
thanks.

**Comment by apseren** [comment]
Can be done in JavaScript with (hour < 12 || hour === 24) ? "AM" : "PM";

Also if your device does not have this bug [https://bugs.chromium.org/p/chromium/issues/detail?id=520783](https://bugs.chromium.org/p/chromium/issues/detail?id=520783) the standard JavaScript API can be used to get the time already formatted.
