### ISSUE TITLE
Notification app Name

### ISSUE THREAD

**Issue by kyrlian** [apseren/ap37#15]
It would be great to have the information on the source app in [getnotifications](https://github.com/apseren/ap37/#getnotifications), to be able to count notifications by app and display count / highlight apps with notifications.

For example `[{id: 0, app:"Gmail", name: "New message"}, ...]`

As a workaround I am using a guess list based on the notification message to try to identify the application for each notification.
https://github.com/kyrlian/ap37/blob/main/notifcount.js

**Comment by apseren** [comment]
Notifications now include the appId to allow to reference the app that generated them. A new method to fetch notifications already grouped by each app was also added. 46440bcb0e9bd8b7984f439c55cd518d6aaef482
