### ISSUE TITLE
Improve dev environment

### ISSUE THREAD

**Issue by sebassdc** [apseren/ap37#7]
I'll like to modify the code on a external file. It will be nice to have a file import from the disk or a gist. Also a nice testing environment

**Comment by apseren** [comment]
When you make changes and save the script in the launcher it will save it to .js file in the phone storage. If you change that file using an external app, such as a text editor, the launcher will pick that changes the next time it is started.

**Comment by Virtuos86** [comment]
> If you change that file using an external app, such as a text editor, the launcher will pick that changes the next time it is started.

This action does not work. Or explain me what means "the next time the launcher is started" please.
Because when i add in an editor of the launcher any simple instruction e.g. `alert("Hi!")` I've got an alert's dialog only one time - when I touch a save button in the editor.
Very strange thing for me.

**Comment by apseren** [comment]
The launcher is not a web browser with a page open to render its ui. `alert("Hi!")` is not a supported instruction. The way to print text on the screen is `ap37.print(0, 0, 'text', '#666666');` as described here: https://github.com/apseren/ap37/blob/master/README.md

**Comment by Virtuos86** [comment]
> 
> 
> The launcher is not a web browser with a page open to render its ui. `alert("Hi!")` is not a supported instruction. The way to print text on the screen is `ap37.print(0, 0, 'text', '#666666');` as described here: https://github.com/apseren/ap37/blob/master/README.md

ok, sorry. no more questions
