### ISSUE TITLE
How to get notification count and append to app name?

### ISSUE THREAD

**Issue by adriancs2** [apseren/ap37#9]
for example:
```
_WhatsApp (2)
```
Anyone has the solution of the coding modification?

**Comment by apseren** [comment]
App notifications count is not yet supported.

**Comment by apseren** [comment]
Notifications now include the appId to allow to reference the app that generated them. A new method to fetch notifications already grouped by each app was also added. 46440bcb0e9bd8b7984f439c55cd518d6aaef482
